FROM nginx:1.23.3
## belki stable tagi ile nginx image ini sağlam ve güncel bir versiyonunu kullanabiliriz
# FROM nginx:stable

RUN apt-get -y update && apt-get -y upgrade

# RUN apt-get update
# RUN apt-get -y upgrade  
RUN apt-get -y install nano
RUN apt-get -y install cron

# RUN apt-get -y install certbot (gerek yok aşağıdaki yeterli?)
RUN apt-get -y install python3-certbot-nginx
#aşağıda sertifika istediğin bütün domainleri yazıyorsun (image oluştururken serverdan yollamakta sıkıntı yaşıyor isteği sahipliği onaylayamıyor)
# RUN certbot certonly --nginx --non-interactive --agree-tos --email serhatkeskin710@gmail.com --domains uniclubs.co,api.uniclubs.co,demo.uniclubs.co,dj.uniclubs.co,metu.uniclubs.co,ostim.uniclubs.co,pm.uniclubs.co,sks.uniclubs.co,test-api.uniclubs.co,test-dj.uniclubs.co,test-main.uniclubs.co,test-pm.uniclubs.co,www.uniclubs.co
